services:
  task-tracker:
    build: .
    container_name: task-tracker-app
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:9090:9090"
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    networks:
      - shared-network

  postgres:
    image: postgres:15
    container_name: postgres-dev
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - shared-network

  redis:
    image: redis:7.2
    container_name: redis-task-tracker
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - shared-network

volumes:
  postgres_data:
  redis_data:

networks:
  shared-network:
    external: true