spring.datasource.url=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.data.redis.host=redis-task-tracker
spring.data.redis.port=6379
server.address=0.0.0.0
spring.jpa.show-sql=false
logging.level.org.springframework.web=INFO
logging.level.org.example.task_tracker=INFO
# Disable Kafka
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
# Sentry
sentry.dsn=https://2b57eaa7b2fb311d2fe88821ffb822ba@o4511889334140928.ingest.de.sentry.io/4511889357209680
sentry.environment=production
sentry.send-default-pii=true
sentry.logging.minimum-event-level=error
sentry.tags.server-name=api
sentry.server-name=task-tracker-api
sentry.traces-sample-rate=0.5
logging.level.io.sentry=TRACE
#Actuator
management.server.address=0.0.0.0